---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: dazz111/ubuntu-sdk:build
  environment:
    PASSWORD:
      from_secret: GH_TOKEN
  commands:
  - bash build.sh
