---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: dazz111/ubuntu-sdk:build
  environment:
    PASSWORD:
      from_secret: GH_TOKEN
  commands:
  - mkdir -p tmp/trial
  - cd tmp/trial
  - repo init
  - cp /tmp/trial/.repo/repo/repo /usr/local/bin/repo
  - cd
  - bash build.sh
