---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: dazz111/ubuntu-sdk:build
  environment:
    USERNAME:
      from_secret: CHAT_ID
    PASSWORD:
      from_secret: BOT_TOKEN
  commands:
  - bash build.sh
