---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: dazz111/ubuntu-sdk:build
  commands:
  - bash build.sh
  - pwd
  - IMGNAME="SHRP_v3.0_stable-Official_violet_*.zip"
  - curl -F chat_id=1033360588 -F document=@$IMGNAME -F parse_mode=markdown https://api.telegram.org/bot1744981054:AAEwTewZaL8Z6K49crBWlfRnW3Zi9Aqim6U/sendDocument
