---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: dazz111/ubuntu-sdk:build
  environment:
    PASSWORD:
      from_secret: GH_TOKEN
  commands:
  - mkdir -p tmp/trial
  - cd tmp/trial
  - repo init --depth=1 -u git://github.com/SHRP/platform_manifest_twrp_omni.git -b v3_9.0 -g default,-device,-mips,-darwin,-notdefault
  - cp /drone/src/tmp/trial/.repo/repo/repo /usr/local/bin/repo
  - cd
  - bash build.sh
